version = "3.8.3"
runner.dialect = scala213source3
maxColumn = 100
align.preset = more
rewrite.rules = [SortImports, RedundantBraces, RedundantParens]
docstrings.style = Asterisk
trailingCommas = multiple
