#!/usr/bin/env bash
# Mutation testing for the @pure modules.
#
# Why a script rather than plain `sbt stryker`: stryker4s 0.16.1 has two
# constraints that a multi-module build trips over.
#
#   1. It reads its config ONLY from <build-root>/stryker4s.conf. A per-module
#      stryker4s.conf is ignored, and -Dstryker4s.* system properties do not
#      override it (it parses the file directly rather than via ConfigFactory.load).
#      So scoping the mutate globs to one module means writing that file per run.
#
#   2. It runs the tests of sbt's CURRENT PROJECT, not of the project the task is
#      scoped to. `sbt foundations/stryker` therefore runs against the root
#      aggregate — which has no test framework on its classpath — and every mutant
#      comes back NoCoverage. `sbt "project foundations" stryker` is what works.
#
# Usage:
#   scripts/stryker.sh                  # every pure module
#   scripts/stryker.sh foundations      # one module
set -euo pipefail

cd "$(dirname "$0")/.."

CONF=stryker4s.conf
BACKUP="$(mktemp -t stryker4s.conf)"
[[ -f "$CONF" ]] && cp "$CONF" "$BACKUP"

# Always put the committed config back, however we exit.
restore() {
  if [[ -f "$BACKUP" ]]; then cp "$BACKUP" "$CONF"; rm -f "$BACKUP"; fi
}
trap restore EXIT INT TERM

# The @pure modules are the mutation targets; boundary/IO modules are not.
PURE_MODULES=(foundations normalization)
MODULES=("${@:-${PURE_MODULES[@]}}")

failed=()
for module in "${MODULES[@]}"; do
  echo "==> stryker: $module"

  cat > "$CONF" <<EOF
# GENERATED by scripts/stryker.sh for module '$module' — do not edit.
# The committed default is restored when the script exits.
stryker4s {
  mutate = ["modules/$module/src/main/scala/**/*.scala"]
  thresholds { high = 90, low = 85, break = 80 }
  reporters = ["console", "html"]
}
EOF

  # Stale .bak dirs from an interrupted run make the next compile fail.
  rm -rf "target/scala-2.13/test-classes.bak" "modules/$module/target/scala-2.13"/*.bak 2>/dev/null || true

  if ! sbt -batch "project $module" stryker; then
    failed+=("$module")
  fi
done

if (( ${#failed[@]} )); then
  echo "==> mutation gate FAILED for: ${failed[*]}" >&2
  exit 1
fi
echo "==> mutation gate passed for: ${MODULES[*]}"
